version: '3'
services:
  mysql:
        container_name: mysql
        build: ./mysql
        environment:
            MYSQL_ROOT_PASSWORD: 123765
        ports:
            - "3306:3306"
        volumes:
        #    - /nacos-cluster/mysql/init:/docker-entrypoint-initdb.d/ #初始化nacos的数据库文件
            - /nacos-cluster/mysql/data/:/var/lib/mysql/   #mysql数据目录
            - /nacos-cluster/mysql/logs/:/var/log/mysql/   #mysql的日志目录
            - /nacos-cluster/mysql/conf/:/etc/mysql/conf.d/  #mysql的配置目录
        command: [
            '--character-set-server=utf8mb4',
            '--collation-server=utf8mb4_unicode_ci',
            '--lower_case_table_names=1'
                ]
        restart: always
  nacos1:
        hostname: nacos1
        container_name: nacos1
        image: nacos/nacos-server
        environment:
        - MODE=cluster
        - NACOS_SERVERS=45.32.108.28:8000 45.32.108.28:8001 45.32.108.28:8002
        - PREFER_HOST_MODE=hostname
        - SPRING_DATASOURCE_PLATFORM=mysql
        - MYSQL_SERVICE_HOST=mysql #Mysql的主机号，同一台机器不能使用IP，直接使用容器名
        - MYSQL_SERVICE_PORT=3306
        - MYSQL_SERVICE_DB_NAME=nacos_config
        - MYSQL_SERVICE_USER=root
        - MYSQL_SERVICE_PASSWORD=123765
        - MYSQL_DATABASE_NUM=1
        - MYSQL_SERVICE_DB_PARAM=characterEncoding=utf8&connectTimeout=10000&socketTimeout=30000 #控制数据库连接时间
        - JVM_XMS=256m
        - JVM_XMX=256m
        - JVM_XMN=256m
        ports:
            - "8000:8848"
        volumes:
            - /nacos-cluster/nacos/nacos1-logs/:/home/nacos/logs/
            - /nacos-cluster/nacos/nacos1-config:/home/nacos/init.d/
        depends_on:
            - mysql
        restart: always
  nacos2:
        hostname: nacos2
        container_name: nacos2
        image: nacos/nacos-server
        environment:
        - MODE=cluster
        - NACOS_SERVERS=45.32.108.28:8000 45.32.108.28:8001 45.32.108.28:8002
        - PREFER_HOST_MODE=hostname
        - SPRING_DATASOURCE_PLATFORM=mysql
        - MYSQL_SERVICE_HOST=mysql
        - MYSQL_SERVICE_PORT=3306
        - MYSQL_SERVICE_DB_NAME=nacos_config
        - MYSQL_SERVICE_USER=root
        - MYSQL_SERVICE_PASSWORD=123765
        - MYSQL_DATABASE_NUM=1
        - MYSQL_SERVICE_DB_PARAM=characterEncoding=utf8&connectTimeout=10000&socketTimeout=30000
        - JVM_XMS=256m
        - JVM_XMX=256m
        - JVM_XMN=256m
        ports:
            - "8001:8848"
        volumes:
            - /nacos-cluster/nacos/nacos2-logs/:/home/nacos/logs/
            - /nacos-cluster/nacos/nacos2-config:/home/nacos/init.d/
        depends_on:
            - mysql
        restart: always
  nacos3:
        hostname: nacos3
        container_name: nacos3
        image: nacos/nacos-server
        environment:
        - MODE=cluster # 集群模式
        - NACOS_SERVERS=45.32.108.28:8000 45.32.108.28:8001 45.32.108.28:8002
        - PREFER_HOST_MODE=hostname
        - SPRING_DATASOURCE_PLATFORM=mysql
        - MYSQL_SERVICE_HOST=mysql
        - MYSQL_SERVICE_PORT=3306
        - MYSQL_SERVICE_DB_NAME=nacos_config
        - MYSQL_SERVICE_USER=root
        - MYSQL_SERVICE_PASSWORD=123765
        - MYSQL_DATABASE_NUM=1
        - MYSQL_SERVICE_DB_PARAM=characterEncoding=utf8&connectTimeout=10000&socketTimeout=30000
        - JVM_XMS=256m
        - JVM_XMX=256m
        - JVM_XMN=256m
        ports:
            - "8002:8848"
        volumes:
            - /nacos-cluster/nacos/nacos2-logs/:/home/nacos/logs/
            - /nacos-cluster/nacos/nacos2-config:/home/nacos/init.d/
        depends_on:
            - mysql
        restart: always
  nginx:
        container_name: nginx
        image: nginx
        ports:
            - "9000:9000"
        volumes:
            - /nacos-cluster/nginx/nginx-logs:/var/log/nginx/
            - /nacos-cluster/nginx/nginx-config:/etc/nginx/conf.d/
            - /nacos-cluster/nginx/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - nacos1
            - nacos2
            - nacos3
        restart: always
        ulimits:
          nproc: 65535
          nofile:
            soft: 65535
            hard: 65535
