server:
  port: 8840

spring:
  application:
    name: MyProviderNacosPayment
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848   #nacos注册中心地址
        cluster-name: HZ  #nacos集群配置，表示该微服务属于哪个集群，基于nacos的服务多级存储模型，服务->集群->实例

