server:
  port: 8006
spring:
  application:
    name: MyProviderConsulPayment   # 本模块，服务的名称
  cloud:
    # 注册中心的配置
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}    # 向外暴露本服务，即注册到consul中

