spring:
  rabbitmq:
    host: 47.98.138.53
    port: 5672
    virtual-host: /
    username: wanyi
    password: 123765
    listener:
      simple:
        prefetch: 1   #控制消费者预取的消费数量，改成1，表示每个消费者先从消息队列中拿一个消息。