#server:
#  port: 2345
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/springcloud_account?serverTimezone=GMT&useSSL=false&characterEncoding=utf-8
#    username: root
#    password: 123765
#    driver-class-name: com.mysql.cj.jdbc.Driver
#mybatis:
#  mapper-locations: mapper/*.xml
#  configuration:
#    map-underscore-to-camel-case: true