server:
  port: 9527
spring:
  application:
    name: MyGateway
  cloud:
    gateway:
      routes:
        - id: payment_routh #路由的ID，没有固定规则但要求唯一，建议配合服务名
#          uri: http://localhost:8001   #匹配后提供服务的路由地址
          uri: lb://MyProviderPayment
          predicates:
            - Path=/payment/eureka/**   #断言,路径相匹配的进行路由

        - id: payment_routh2
#          uri: http://localhost:8001
          uri: lb://MyProviderPayment   #使用服务名进行路由，需要开启discovery.locator.enabled=true
          predicates:
            - Path=/payment/eureka/lb   #断言,路径相匹配的进行路由
            - After=2021-10-26T22:48:16.597+08:00[Asia/Shanghai]
          filter:
            - AddRequestHeader=Truth,zhangsan is freaking awesome!
      discovery:
        locator:
          enabled: true   #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      default-filters:  # 这里是默认路由作用每一个路由


      # 注意：路由实例过滤器(配置在路由里面),defaultFilter,globalFilter，这三个路由器是根据order排序的
      # 如果order值相同，则defaultFilter>路由实例过滤器>globalFilter

eureka:
  client:
    register-with-eureka: true  #是否注册进服务注册中心
    fetchRegistry: true   # 是否从服务注册中心抓取已有的注册信息，默认为true，单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    service-url:  # 配置eureka结点
      defaultZone: http://localhost:7001/eureka  # 单机版

