server:
  port: 80
spring:
  application:
    name: MyConsumerNacosOrder
  cloud:
    nacos:
      discovery:
#        server-addr: localhost:8848 #nacos服务器地址
        cluster-name: HZ  #本微服务地址
#        namespace:    #命名空间的配置，nacos用来做环境隔离的，dev,pro等等,不同命名空间的服务，不能互相访问
#MyProviderNacosPayment:   #指定某个服务名称，实现更改单个请求该服务时选择指定的负载均衡规则
#  ribbon:
#    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule #负载均衡规则，可以优先寻找与自己同集群的服务
    #配置好nacos集群后，可以实现优先访问集群内部服务，如果内部服务失效再访问外部服务，另外访问集群内部服务，是随机的负载均衡算法
