server:
  port: 80
spring:
  application:
    name: MyConsumerFeign
eureka:
  client:
    register-with-eureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://eureka7001:7001/eureka,http://eureka7002:7002/eureka  # 集群版

# openfeign的超时控制
#feign:
#  client:
#    config:
#      default:  #全局设置，设置的是feign内部ribbon的配置
#        connectTimeout: 5000  # 指的是建立连接所用的时间，适用于网路状况正常情况下，两端连接所用的时间
#        readTimeout: 5000   # 指的是建立连接后从服务器读取到可用资源所用的时间


